# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'newserviceconnection'
    displayName: 'Docker Login'

- script: |
    docker pull marcosap31/apporderingsystem-angular:v3
  displayName: 'Docker Pull v3'


# - task: Docker@2
#  inputs:
#    repository: 'marcosap31/apporderingsystem-angular'
#    command: 'build'
#    Dockerfile: 'Dockerfile'  # Asegúrate de tener un Dockerfile en la ubicación correcta
#    tags: 'v3'
#    displayName: 'Docker Build'

#- task: Docker@2
#  inputs:
#    repository: 'marcosap31/apporderingsystem-angular'
#    command: 'push'
#    tags: 'v3'
#    displayName: 'Docker Push'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'appServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp config container set --name 'appinventory' --resource-group 'CMPRG1DEV-RG-APPSRV001' --docker-custom-image-name 'marcosap31/apporderingsystem-angular:v3' --docker-registry-server-url 'https://index.docker.io/v1/'
      az webapp restart --name 'appinventory' --resource-group 'CMPRG1DEV-RG-APPSRV001'
  displayName: 'Azure Web App Container Deploy'



  
  





  

  